### ISSUE TITLE
Some improvement

### ISSUE THREAD

**Issue by OiziZ** [sonalys/animeman#1]
Hi,

Your script works well and is much lighter than Sonarr.
Is it possible to add these two features?

- Compatibility with the yggtorrent site (private tracker)
- To be able to filter results via variables (ex VO Required and Uncensored Preferred)

Thanks

**Comment by sonalys** [comment]
* For adding compatibility with other sources is not in my scope, if someone wants to implement it, I can review and merge.
* I think adding the option to input your own nyaa.si custom URL would suffice for this in a dynamic manner, I will work on it

**Comment by sonalys** [comment]
I created a customParameters config for RSS to inject query parameters on the rss request.

There is an example in the Readme. Let me know if that works for you
