### ISSUE TITLE
Problem with dates format and add Kitsu in the AnimeList types

### ISSUE THREAD

**Issue by IsAy15** [sonalys/animeman#2]
As an european people I use the DD-MM-YY date format and it cause a problem in the function convertEntry from myanimelist's anime_list.go file

Could be great to implement Kitsu in the AnimeList types

**Comment by IsAy15** [comment]
I fixed but now it works only for european people and I'm too bad with Go to add Kitsu, I don't think I'll continue to work on the fork

**Comment by sonalys** [comment]
If I have the API response from MAL with the entry that gave problem, or how to reproduce it I can try to increment over your fix.
If you could send it to me that would be nice.

**Comment by IsAy15** [comment]
myanimelist/anime_list.go : line 23

I changed the format from 01-02-06 to 02-01-06 to make it works for me

**Comment by sonalys** [comment]
> myanimelist/anime_list.go : line 23
> 
> I changed the format from 01-02-06 to 02-01-06 to make it work for me

Yeah, that definitely needs more clarification to work on both cases. The MAL api doesn't provide the format in which it is responding. I will look at the request headers later.

Does it use this format for one entry or all of them?

could you please provide a request containing this response?

**Comment by IsAy15** [comment]
It seems that all the entries use this format but you can look at list [here](https://myanimelist.net/animelist/IsAy1/load.json) if you want to

**Comment by sonalys** [comment]
Very interesting, it's totally different based on the user. 

I think the only solution would be brute force the format that works for all entries.

This load.json is not very reliable

**Comment by sonalys** [comment]
I added some custom logic for asserting the time format for now. It tries to brute force the mask that works for all entries without errors.

I will close this issue.
